server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /products {
        proxy_pass http://product-service:5001/products;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /orders {
        proxy_pass http://order-service:5002/orders;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /payment {
        proxy_pass http://payment-service:5003/payment;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /notify {
        proxy_pass http://notification-service:5004/notify;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
